# Generated by Django 4.0.4 on 2022-04-28 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSAPI.folders')),
                ('topics', models.ManyToManyField(to='FSAPI.topics')),
            ],
            options={
                'db_table': 'Folders',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=4096)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSAPI.documents')),
                ('topics', models.ManyToManyField(to='FSAPI.topics')),
            ],
            options={
                'db_table': 'Documents',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='folders',
            index=models.Index(fields=['parent', 'name'], name='Folders_parent__65b5a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='folders',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='fsapi_folders_unique_path'),
        ),
        migrations.AddIndex(
            model_name='documents',
            index=models.Index(fields=['parent', 'name'], name='Documents_parent__215cc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='documents',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='fsapi_documents_unique_path'),
        ),
    ]
