# Generated by Django 4.0.4 on 2022-04-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FSAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inode',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='inode',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='FSAPI.folder'),
        ),
        migrations.AddIndex(
            model_name='inode',
            index=models.Index(fields=['parent', 'name'], name='INodes_parent__14ba2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='inode',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='fsapi_inode_unique_path'),
        ),
    ]
