# Generated by Django 4.0.4 on 2022-04-28 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FSAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FSAPI.folders'),
        ),
    ]
