# Generated by Django 4.0.4 on 2022-04-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSAPI', '0002_remove_inode_parent_id_inode_parent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inode',
            name='fsapi_inode_unique_path',
        ),
        migrations.RemoveIndex(
            model_name='inode',
            name='INodes_parent__14ba2d_idx',
        ),
        migrations.RemoveField(
            model_name='inode',
            name='parent',
        ),
        migrations.AlterField(
            model_name='inode',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='inode',
            index=models.Index(fields=['name'], name='INodes_name_5caa60_idx'),
        ),
    ]
