# Generated by Django 4.0.4 on 2022-04-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FSAPI', '0003_remove_inode_fsapi_inode_unique_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inode',
            name='name',
            field=models.CharField(max_length=4096, unique=True),
        ),
    ]
